// usb_utmi_top.v -- the UTMI digital top (issue #52): the single HDL
// toplevel for this repo's whole digital half.
//
// It instantiates `usb_tx_serializer.v` and `usb_rx_path.v` **unmodified**
// and adds the two things neither of them could own on its own:
//
//   1. the TX-side 30 <-> 144 MHz clock-domain crossings that
//      `spec/decision-records/0001-clocking-cdc-jitter-metric-and-pvt-envelope.md`
//      ("decision record #9") Decision 3's per-signal CDC table specifies
//      but `usb_tx_serializer.v`'s header explicitly defers ("that
//      crossing ... is integration-level work for a future issue"); and
//   2. the per-domain (asynchronous-assert / synchronous-deassert) reset
//      synchronizers Decision 3's "Reset scheme" specifies, for the logic
//      this top itself owns.
//
// Everything below is fixed by the ratified spec plus that decision
// record; nothing here relaxes or reinterprets either. Where this module
// makes an integration-level choice the record does not spell out (the
// `TxReady` acknowledge crossing, the `OpMode == 2'b01` / `SuspendM == 0`
// driver gating, the `DataOut` skew guard), the choice and its derivation
// are stated explicitly below rather than left implicit in the code.
//
// =====================================================================
// Port table -- cross-referenced to decision record #9, Decision 4
// =====================================================================
// Every row of Decision 4's "Full UTMI port table" appears here
// name-for-name and width-for-width. The last block is the pad-side
// interface owed to the sibling analog canaries (`spec/usb2-phy.md` §6),
// which Decision 4's UTMI-only table does not cover.
//
// | Port              | Dir | W | Decision 4 row / source                 |
// |-------------------|-----|---|-----------------------------------------|
// | `Clock`           | out | 1 | `Clock` -- "30 MHz UTMI interface clock  |
// |                   |     |   | (Decision 2); this repo's PHY is the     |
// |                   |     |   | clock source". Driven from `clk_utmi`    |
// |                   |     |   | (Decision 2: PLL-supplied, see below).   |
// | `Reset`           | in  | 1 | `Reset` -- active-high, asynchronous.    |
// | `TxValid`         | in  | 1 | `TxValid` -- level, held with `DataOut`  |
// |                   |     |   | stable until `TxReady` acknowledges.     |
// | `TxReady`         | out | 1 | `TxReady` -- PHY's byte acknowledge.     |
// | `DataOut[7:0]`    | in  | 8 | `DataOut[7:0]` -- byte to transmit, not  |
// |                   |     |   | yet NRZI-encoded or bit-stuffed.         |
// | `RxValid`         | out | 1 | `RxValid` -- one `Clock` cycle per byte. |
// | `RxActive`        | out | 1 | `RxActive` -- SOP..EOP indicator.        |
// | `RxError`         | out | 1 | `RxError` -- stuff/framing error.        |
// | `DataIn[7:0]`     | out | 8 | `DataIn[7:0]` -- received byte.          |
// | `LineState[1:0]`  | out | 2 | `LineState[1:0]` -- `{D-, D+}` raw       |
// |                   |     |   | electrical sample, not pre-encoded J/K.  |
// | `OpMode[1:0]`     | in  | 2 | `OpMode[1:0]` -- `00` normal, `01`       |
// |                   |     |   | non-driving, `10` bit-stuff/NRZI bypass, |
// |                   |     |   | `11` reserved.                           |
// | `TermSelect`      | in  | 1 | `TermSelect` -- FS termination select.    |
// | `XcvrSelect[1:0]` | in  | 2 | `XcvrSelect` -- "2 (canonical UTMI       |
// |                   |     |   | width; only the FS encoding is wired)".  |
// | `SuspendM`        | in  | 1 | `SuspendM` -- active-low suspend.         |
// | `clk_144`         | in  | 1 | Decision 1/2: 144 MHz oversampling clock, |
// |                   |     |   | PLL-supplied (not generated here).       |
// | `clk_utmi`        | in  | 1 | Decision 2: 30 MHz UTMI clock, co-        |
// |                   |     |   | generated by the same PLL. Presented to   |
// |                   |     |   | the link controller as `Clock`.          |
// | `dp` / `dm`       | in  | 1 | `spec/usb2-phy.md` §6, differential-      |
// |                   |     |   | receiver row: digitized pad-level D+/D-. |
// | `tx_drive_en`     | out | 1 | §6, current-mode driver row: "Control     |
// | `tx_oe`           | out | 1 | interface from UTMI layer -- differential |
// | `tx_dp`           | out | 1 | drive enable, output enable (OE), TxD+/   |
// | `tx_dn`           | out | 1 | TxD- data lines."                        |
//
// Deliberately **not** brought out: `usb_rx_path.v`'s `BusReset`/`Suspend`
// status outputs. They are not rows of Decision 4's table (that module's
// own header says they exist "beyond the literal UTMI port table"), and
// this top's acceptance criterion is a port list that matches the table.
// A link controller derives bus reset / suspend from `LineState`, which is
// exposed. The RX path keeps them for its own testbench.
//
// =====================================================================
// Clocking (Decision 2)
// =====================================================================
// Both clocks are *inputs*: Decision 2 fixes the 30 MHz UTMI clock as a
// second PLL output co-generated with the 144 MHz oversampling clock from
// a shared VCO. Per CLAUDE.md's scope-discipline rule this repo does not
// design that PLL, so neither clock is generated here. `Clock` (Decision
// 4's PHY -> Link port) is the PHY's presentation of `clk_utmi` to the
// link controller.
//
// =====================================================================
// CDC (Decision 3), signal by signal
// =====================================================================
// 30 -> 144 MHz, all 2-flop synchronizers per Decision 3's depth choice:
//
//   `OpMode[1:0]`, `TermSelect`, `XcvrSelect[1:0]`, `SuspendM`
//       Quasi-static control. Straight 2-flop synchronizer per bit,
//       exactly as the table's rows say. Multi-bit fields (`OpMode`,
//       `XcvrSelect`) are quasi-static: the link controller does not
//       reconfigure them mid-packet, so per-bit skew during a change is
//       not a correctness hazard (this is the table's own "quasi-static"
//       qualifier, not an assumption added here).
//
//   `TxValid` (+ one extra destination-domain flop -- see below)
//       Level, held until acknowledged (Decision 3's `TxValid` row:
//       "request/acknowledge handshake, not a single-cycle pulse").
//
//   `DataOut[7:0]`
//       Decision 3's row says DataOut is "sampled into the 144 MHz domain
//       in the same cycle `TxValid` is acknowledged ... no separate
//       byte-wide synchronizer; correctness relies on the
//       `TxValid`/`TxReady` handshake". That is a multi-cycle-path (MCP)
//       formulation, and this top honours it: `usb_tx_serializer.v`
//       samples the byte on its own bit-time edge, gated by `TxValid`.
//       This top additionally retimes each bit through the same 2-flop
//       stage used for the control inputs. That is a strict superset of
//       what the record requires -- it adds metastability hardening at the
//       domain boundary, and the bit-to-bit skew a per-bit synchronizer
//       could introduce is harmless *because* of the MCP window the
//       handshake guarantees: the link holds `DataOut` stable from the
//       cycle it asserts `TxValid` until the acknowledge, and consecutive
//       acknowledges are >= 8 FS bit times (>= 666 ns) apart, versus a
//       2-cycle (13.9 ns) crossing latency.
//
//   The one case where that MCP window is *not* automatically wide is the
//   very first byte of a packet, where the link raises `TxValid` in the
//   same UTMI cycle it first presents `DataOut`: the serializer may reach
//   its next bit-time edge only one or two 144 MHz cycles later. A
//   skew-guard flop closes it: `TxValid` crosses through the 2-flop
//   synchronizer **plus one destination-domain pipeline flop**, so by the
//   edge on which `txvalid_144` first reads 1, every `DataOut` bit has
//   already been stable in the 144 MHz domain for a full cycle. The extra
//   flop is a pipeline delay in the destination domain, **not** a third
//   synchronizer stage -- Decision 3's 2-flop depth choice is unchanged.
//
// 144 -> 30 MHz:
//
//   `TxReady`
//       Decision 3's row specifies "a 2-flop synchronizer on a level
//       signal generated by the TX state machine". Applying a *plain*
//       level synchronizer to `usb_tx_framer.v`'s `TxReady` would break
//       Decision 4's handshake semantics ("one byte per `TxReady`"): that
//       level is asserted for a whole 83.33 ns FS bit time, i.e. 2.5
//       periods of the 33.33 ns UTMI clock, so the link controller would
//       observe it asserted on 2 or 3 consecutive UTMI cycles and hand
//       over 2-3 bytes for the single byte the serializer actually took.
//
//       Chosen scheme (stated here, and tested -- see
//       `verification/test_usb_utmi_top.py`): a **toggle (pulse)
//       synchronizer**. The 144 MHz domain detects the serializer's own
//       byte-capture event (the falling edge of its `TxReady` level while
//       `txvalid_144` is high -- the same edge `verification/test_usb_tx.py`
//       already uses as "the clock edge that just captured the current
//       byte"), toggles a level on it, crosses that level with **Decision
//       3's 2-flop synchronizer**, and edge-detects it in the UTMI domain
//       to produce a **one-cycle** `TxReady` pulse. The crossing itself is
//       therefore exactly the 2-flop level synchronizer the record
//       specifies; the destination-domain edge detector (which the record
//       does not itself address) is what preserves "one byte per
//       `TxReady`".
//
//       Why the falling edge of `TxReady` is exactly "a byte was
//       captured": `usb_tx_framer.v` asserts `TxReady` only in `ST_IDLE`
//       and in `ST_DATA` when `byte_idx == 7 && stuff_consume`. All of its
//       inputs change only on `bit_stb` edges, so `TxReady` is constant
//       within a bit time and can only fall on a bit-time edge. Leaving
//       `ST_IDLE` requires `TxValid` and captures a byte; leaving
//       `byte_idx == 7 && stuff_consume` either captures the next byte
//       (when `TxValid` is high) or ends the packet (when it is not) --
//       which is why the detector below is gated with `txvalid_144`, so an
//       end-of-packet fall never fabricates an acknowledge for a byte the
//       link never handed over.
//
//       Toggle-synchronizer liveness requirement (successive events must
//       be at least 2 destination cycles apart) is met by a wide margin:
//       byte captures are >= 8 FS bit times = 666 ns = 20 UTMI cycles
//       apart, and the first two are 16 bit times apart (SYNC + byte 0).
//
//   The RX-side crossings (`RxValid`/`DataIn` elastic FIFO,
//   `RxActive`/`RxError`/`LineState` 2-flop synchronizers) are already
//   implemented inside `usb_rx_cdc.v` and are not duplicated here.
//
// Reset (Decision 3's "Reset scheme"): `Reset` is asynchronous and
// active-high. This top derives its own `rst_144_n`/`rst_utmi_n` with the
// same async-assert / sync-deassert pattern `usb_rx_cdc.v` uses, one
// synchronizer per domain, for the logic it owns (the TX serializer and
// the crossings above). `usb_rx_path.v` keeps its own internal pair for
// the RX side; both pairs are the same structure on the same clocks fed
// from the same asynchronous `Reset`, and nothing crosses *between* them
// that would require them to be the same physical net.
//
// =====================================================================
// `OpMode` and `SuspendM` at the pad-side driver interface
// =====================================================================
// `usb_tx_serializer.v` implements Decision 4's `OpMode == 2'b10`
// (bit-stuffing/NRZI bypass) itself. It does **not** implement `2'b01`
// ("Non-driving (TX drivers disabled)"), because disabling the drivers is
// an act on the pad-side control interface, which only exists at this
// level. This top therefore gates `tx_drive_en`/`tx_oe` -- and, for the
// same reason, gates them under `SuspendM == 0` (Decision 4: "commands the
// PHY into suspend/low-power state"; a suspended PHY must not drive the
// bus). `tx_dp`/`tx_dn` pass through unchanged: with both enables
// deasserted the driver is off and its data inputs are don't-care. Neither
// gate touches `usb_tx_serializer.v`, whose FSM continues to run (and to
// acknowledge bytes) exactly as it does in normal operation.
//
// `XcvrSelect`/`TermSelect` are synchronized here because Decision 3's
// table specifies the crossing, but they have **no consumer inside this
// repo**: `TermSelect`'s consumer is the pull-up/pull-down and termination
// control interface (`spec/usb2-phy.md` §6) owned by a sibling analog
// canary, and Decision 4 states this FS-only device treats every
// `XcvrSelect` encoding as don't-care. No fake load is invented for
// either; their synchronized 144 MHz-domain nets (`term_select_144`,
// `xcvr_select_144`) are the attachment point for that future consumer,
// and are verified as synchronizers by this repo's testbench. A synthesis
// run will prune them until a consumer exists -- expected, and recorded
// here rather than hidden.

`default_nettype none

module usb_utmi_top #(
    // Passed straight through to usb_rx_path.v / usb_rx_framer.v. Defaults
    // are the spec-correct values (2.5 us reset / 3 ms suspend detection at
    // 144 MHz); a testbench MAY override them to keep a detection test's
    // simulated cycle count tractable -- see usb_rx_path.v's header.
    parameter integer RESET_DETECT_CYCLES   = 360,
    parameter integer SUSPEND_DETECT_CYCLES = 432_000,
    parameter integer MAX_PACKET_CYCLES     = 200_000
) (
    // ---- PLL-supplied clocks (Decision 2) ----
    input  wire        clk_144,
    input  wire        clk_utmi,

    // ---- UTMI port table (decision record #9, Decision 4) ----
    output wire        Clock,
    input  wire        Reset,

    input  wire        TxValid,
    output wire        TxReady,
    input  wire [7:0]  DataOut,

    output wire        RxValid,
    output wire        RxActive,
    output wire        RxError,
    output wire [7:0]  DataIn,

    output wire [1:0]  LineState,

    input  wire [1:0]  OpMode,
    input  wire        TermSelect,
    input  wire [1:0]  XcvrSelect,
    input  wire        SuspendM,

    // ---- pad-side interface (spec/usb2-phy.md §6, sibling canaries) ----
    input  wire        dp,
    input  wire        dm,
    output wire        tx_drive_en,
    output wire        tx_oe,
    output wire        tx_dp,
    output wire        tx_dn
);

    // ---- Decision 4: the PHY sources the UTMI interface clock ----------
    assign Clock = clk_utmi;

    // ---- per-domain reset synchronizers (Decision 3, reset scheme) -----
    // Same structure as rtl/usb_rx_cdc.v: asynchronous assert, synchronous
    // deassert, one local synchronizer per domain, both fed from `Reset`.
    reg [1:0] rst144_meta;
    always @(posedge clk_144 or posedge Reset) begin
        if (Reset) rst144_meta <= 2'b00;
        else       rst144_meta <= {rst144_meta[0], 1'b1};
    end
    wire rst_144_n = rst144_meta[1];

    reg [1:0] rstutmi_meta;
    always @(posedge clk_utmi or posedge Reset) begin
        if (Reset) rstutmi_meta <= 2'b00;
        else       rstutmi_meta <= {rstutmi_meta[0], 1'b1};
    end
    wire rst_utmi_n = rstutmi_meta[1];

    // ---- 30 -> 144 MHz control/data synchronizers (2-flop, Decision 3) --
    // `SuspendM` is active-low, so its synchronizer resets to 1 (not
    // suspended) -- resetting it to 0 would hold the PHY in suspend, and
    // hence its line drivers disabled, until the link controller wrote a
    // value.
    reg        txvalid_s1, txvalid_s2, txvalid_s3;
    reg [7:0]  dataout_s1, dataout_s2;
    reg [1:0]  opmode_s1,  opmode_s2;
    reg [1:0]  xcvrsel_s1, xcvrsel_s2;
    reg        termsel_s1, termsel_s2;
    reg        suspendm_s1, suspendm_s2;

    always @(posedge clk_144 or negedge rst_144_n) begin
        if (!rst_144_n) begin
            txvalid_s1  <= 1'b0;
            txvalid_s2  <= 1'b0;
            txvalid_s3  <= 1'b0;
            dataout_s1  <= 8'h00;
            dataout_s2  <= 8'h00;
            opmode_s1   <= 2'b00;
            opmode_s2   <= 2'b00;
            xcvrsel_s1  <= 2'b00;
            xcvrsel_s2  <= 2'b00;
            termsel_s1  <= 1'b0;
            termsel_s2  <= 1'b0;
            suspendm_s1 <= 1'b1;
            suspendm_s2 <= 1'b1;
        end else begin
            // 2-flop synchronizer (s1 -> s2) on every signal; `txvalid_s3`
            // is the skew-guard pipeline flop described in the header, not
            // a third synchronizer stage.
            txvalid_s1  <= TxValid;
            txvalid_s2  <= txvalid_s1;
            txvalid_s3  <= txvalid_s2;
            dataout_s1  <= DataOut;
            dataout_s2  <= dataout_s1;
            opmode_s1   <= OpMode;
            opmode_s2   <= opmode_s1;
            xcvrsel_s1  <= XcvrSelect;
            xcvrsel_s2  <= xcvrsel_s1;
            termsel_s1  <= TermSelect;
            termsel_s2  <= termsel_s1;
            suspendm_s1 <= SuspendM;
            suspendm_s2 <= suspendm_s1;
        end
    end

    wire       txvalid_144     = txvalid_s3;
    wire [7:0] dataout_144     = dataout_s2;
    wire [1:0] opmode_144      = opmode_s2;
    wire [1:0] xcvr_select_144 = xcvrsel_s2;   // no in-repo consumer (header)
    wire       term_select_144 = termsel_s2;   // no in-repo consumer (header)
    wire       suspendm_144    = suspendm_s2;

    // ---- FS transmit datapath (rtl/usb_tx_serializer.v, unmodified) ----
    wire ser_txready;
    wire ser_tx_drive_en, ser_tx_oe, ser_tx_dp, ser_tx_dn;

    usb_tx_serializer u_tx_serializer (
        .clk         (clk_144),
        .rst_n       (rst_144_n),

        .TxValid     (txvalid_144),
        .TxReady     (ser_txready),
        .DataOut     (dataout_144),
        .OpMode      (opmode_144),

        .tx_drive_en (ser_tx_drive_en),
        .tx_oe       (ser_tx_oe),
        .tx_dp       (ser_tx_dp),
        .tx_dn       (ser_tx_dn)
    );

    // ---- 144 -> 30 MHz `TxReady` acknowledge (toggle synchronizer) -----
    // Falling edge of the serializer's `TxReady` level, qualified by the
    // synchronized `TxValid` the serializer itself sees == "a byte was
    // captured on that bit-time edge" (derivation in the header).
    reg txready_144_q;
    always @(posedge clk_144 or negedge rst_144_n) begin
        if (!rst_144_n) txready_144_q <= 1'b0;
        else            txready_144_q <= ser_txready;
    end

    wire byte_accepted_144 = txready_144_q & ~ser_txready & txvalid_144;

    reg accept_toggle_144;
    always @(posedge clk_144 or negedge rst_144_n) begin
        if (!rst_144_n)               accept_toggle_144 <= 1'b0;
        else if (byte_accepted_144)   accept_toggle_144 <= ~accept_toggle_144;
    end

    // Decision 3's 2-flop synchronizer (`accept_tog_s1`/`_s2`) on the
    // toggle level, plus a destination-domain edge detector (`_s3`) that
    // turns each crossing into the one-cycle acknowledge Decision 4's
    // handshake semantics require.
    reg accept_tog_s1, accept_tog_s2, accept_tog_s3;
    always @(posedge clk_utmi or negedge rst_utmi_n) begin
        if (!rst_utmi_n) begin
            accept_tog_s1 <= 1'b0;
            accept_tog_s2 <= 1'b0;
            accept_tog_s3 <= 1'b0;
        end else begin
            accept_tog_s1 <= accept_toggle_144;
            accept_tog_s2 <= accept_tog_s1;
            accept_tog_s3 <= accept_tog_s2;
        end
    end

    assign TxReady = accept_tog_s2 ^ accept_tog_s3;

    // ---- pad-side line-driver enables (OpMode 2'b01 / SuspendM) --------
    wire non_driving = (opmode_144 == 2'b01) || (suspendm_144 == 1'b0);

    assign tx_drive_en = ser_tx_drive_en & ~non_driving;
    assign tx_oe       = ser_tx_oe       & ~non_driving;
    assign tx_dp       = ser_tx_dp;
    assign tx_dn       = ser_tx_dn;

    // ---- FS receive datapath (rtl/usb_rx_path.v, unmodified) -----------
    // Owns its own 144 -> 30 MHz crossings (usb_rx_cdc.v) and its own
    // per-domain reset synchronizers, both fed from the same async `Reset`.
    usb_rx_path #(
        .RESET_DETECT_CYCLES   (RESET_DETECT_CYCLES),
        .SUSPEND_DETECT_CYCLES (SUSPEND_DETECT_CYCLES),
        .MAX_PACKET_CYCLES     (MAX_PACKET_CYCLES)
    ) u_rx_path (
        .Reset     (Reset),

        .clk_144   (clk_144),
        .dp        (dp),
        .dm        (dm),

        .clk_utmi  (clk_utmi),

        .RxValid   (RxValid),
        .DataIn    (DataIn),
        .RxActive  (RxActive),
        .RxError   (RxError),
        .LineState (LineState),

        // Not rows of Decision 4's port table -- see the header.
        .BusReset  (),
        .Suspend   ()
    );

endmodule

`default_nettype wire
